# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:categories/:title/

# Server
source:           siteSource
destination:      build/jekyll-generated-site
port:             7112
baseurl:          ''
url:              https://statico.io
encoding:         UTF-8

# statico
statico:
  sdk:
    version:      0.1.21