# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           siteSource
destination:      build/jekyll-generated-site
port:             9001
baseurl:          ''
url:              http://www.statico.io
encoding:         UTF-8

# statico
statico:
  sdk:
    version:      0.1.17